spring:
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/oracle/**/*.xml

logging:
  level:
    org.example.springadminv2: DEBUG
    org.mybatis: DEBUG

log:
  event:
    rdb:
      enabled: true
