spring:
  application:
    name: spring-admin-v2
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  type-handlers-package: org.example.springadminv2.global.typehandler
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

security:
  access:
    authority-source: ${AUTHORITY_SOURCE:USER_MENU}

log:
  event:
    rdb:
      enabled: ${LOG_EVENT_RDB_ENABLED:false}
