spring:
  datasource:
    url: jdbc:h2:mem:spider-local;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:db/h2/ddl/security.sql
      data-locations: classpath:db/h2/dml/security.sql
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:mapper/mysql/**/*.xml

logging:
  level:
    org.example.springadminv2: DEBUG
    org.mybatis: DEBUG

log:
  event:
    rdb:
      enabled: true
