spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}:${DB_SID}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-init-sql: ALTER SESSION SET CURRENT_SCHEMA = ${DB_SCHEMA}

pagehelper:
  helper-dialect: oracle
